services:
  s3mock:
    container_name: "${S3MOCK_DOCKER_NAME:-s3mock-main}"
    image: adobe/s3mock:4.11.0
    ports:
      - "127.0.0.1:4566:9090"
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=aligned.storage
      - COM_ADOBE_TESTING_S3MOCK_STORE_REGION=us-east-2

  s3mock2:
    container_name: "${S3MOCK2_DOCKER_NAME:-s3mock-secondary}"
    image: adobe/s3mock:4.11.0
    ports:
      - "127.0.0.1:4567:9090"
    environment:
      - COM_ADOBE_TESTING_S3MOCK_STORE_INITIAL_BUCKETS=aligned.storage
      - COM_ADOBE_TESTING_S3MOCK_STORE_REGION=us-west-1
