# https://hub.docker.com/_/postgres
FROM postgres:16.3

# Environment variables
ENV POSTGRES_USER=tracker_user
ENV POSTGRES_PASSWORD=tracker_pass
ENV POSTGRES_DB=tracker_db

# Expose the default PostgreSQL port
EXPOSE 5432
