[package]
name = "risc0_aggregation_program"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
serde = { version = "1.0.203" }
serde_json = "1.0.117"
risc0-zkvm = { git = "https://github.com/risc0/risc0", tag="v2.0.0", default-features = false, features = ["std"] }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }

[patch.crates-io]
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0", features = ["keccak"]}	

[lib]
path = "./src/lib.rs"

[[bin]]
name = "risc0_aggregator_program"
path = "./src/main.rs"
