apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: "${PROMETHEUS_URL}"
    basicAuth: false
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 1s

  - name: PostgreSQL
    type: postgres
    uid: postgres
    access: proxy
    orgId: 1
    url: "${POSTGRES_HOST}:${POSTGRES_PORT}"
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1600

  - name: "Ethereum RPC"
    type: "yesoreyeram-infinity-datasource"
    typeName: "Infinity"
    uid: "ethereum_rpc"
    access: "proxy"
    url: "${RPC_URL}"
    isDefault: false
    jsonData:
      global_queries: []
    readOnly: false
    editable: true
    basicAuth: false

  # Note: We use this data source for health check calls. The one above is not useful for non-Ethereum calls
  # because the RPC URL is prepended to the one indicated in the panel.
  - name: "HTTP"
    type: "yesoreyeram-infinity-datasource"
    uid: "http"
    access: "proxy"
    url: ""
    isDefault: false
    jsonData:
      global_queries: []

  - name: pg_auto_failover Monitor
    type: postgres
    uid: pgaf_monitor_host
    access: proxy
    orgId: 1
    url: "${MONITOR_DB_HOST}:${MONITOR_DB_PORT}"
    database: "${MONITOR_DB_DB}"
    user: "${MONITOR_DB_USER}"
    secureJsonData:
      password: ""
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      sslmode: require
      postgresVersion: 1700
