SHELL := /bin/bash

generate_circom_groth16_bn256_setup: ## Run the circom_groth16_bn256_script setup
	@echo "Running circom_groth16_bn256 script setup..."
	@cd circuits && ./generate_setup.sh

deploy_contract:

run:
