- import_playbook: setup.yaml
- import_playbook: webserver.yaml
- import_playbook: go.yaml
- import_playbook: rust.yaml
- import_playbook: eigenlayer-cli.yaml

- hosts: aligned-holesky-stage
  become: true
  vars:
    user: "{{ user }}"

  tasks:
    # Create directories for each service
    - name: Create directories for each service if do not exist
      ansible.builtin.file:
        path: /home/{{ user }}/repos/{{ item }}
        state: directory
        mode: '0755'
      become_user: "{{ user }}"
      loop:
          - batcher
          - aggregator
          - operator
          - explorer
          - task_sender

    # Clone Aligned repository for each service
    - name: Clone Aligned repository
      ansible.builtin.git:
        repo: https://github.com/yetanotherco/aligned_layer.git
        dest: /home/{{ user }}/repos/{{ item }}/aligned_layer
        version: v0.9.2
      become_user: "{{ user }}"
      loop:
          - batcher
          - aggregator
          - operator
          - explorer
          - task_sender
