[package]
name = "proof_aggregator"
version = "0.1.0"
edition = "2021"

[dependencies]
serde =  { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
alloy = { workspace = true }
bincode = { workspace = true }
db = { workspace = true }
agg_mode_sdk = { workspace = true }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
c-kzg = "2.1.1"
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"]}
sha3 = "0.10.8"
reqwest = { version = "0.12" }
ciborium = "=0.2.2"
lambdaworks-crypto = { workspace = true }
rayon = "1.10.0"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "uuid", "bigdecimal" ] }

# zkvms
sp1-sdk = { workspace = true }
sp1_aggregation_program = { path = "./aggregation_programs/sp1" }
risc0-zkvm = { workspace = true }
risc0_aggregation_program = { path = "./aggregation_programs/risc0" }
risc0-ethereum-contracts = { git = "https://github.com/risc0/risc0-ethereum/", tag = "v3.0.0" }

[build-dependencies]
sp1-build = { version = "5.0.0" }
risc0-build = { version = "3.0.3" }

[package.metadata.risc0]
# Tell risc0 build to find method in ./aggregation_programs/risc0 package
methods = ["./aggregation_programs/risc0"]

[features]
default = []
prove = []
gpu = ["risc0-zkvm/cuda"]

[[bin]]
name = "proof_aggregator_cpu"
path = "./src/bin/proof_aggregator_cpu.rs"
required-features = ["prove"]

[[bin]]
name = "proof_aggregator_gpu"
path = "./src/bin/proof_aggregator_gpu.rs"
required-features = ["prove", "gpu"]

[[bin]]
name = "proof_aggregator_dev"
path = "./src/bin/proof_aggregator_dev.rs"

[[bin]]
name = "write_program_image_id_vk_hash"
path = "./bin/write_program_image_id_vk_hash.rs"
