deps:
	curl -L https://foundry.paradigm.xyz | bash
	foundryup

anvil-deploy-eigen-contracts:
	@echo "Deploying Eigen Contracts..."
	. scripts/anvil/deploy_eigen_contracts.sh

anvil-start:
	@echo "Starting Anvil..."
	. scripts/anvil/start.sh
