aligned_service_manager_address: <aligned_service_manager_address>
proof_aggregation_service_address: <proof_aggregation_service_address>
eth_rpc_url: <eth_rpc_url>
eth_ws_url: <eth_ws_url>
max_proofs_in_queue: 1000
# How far in the past should the service go to fetch batch logs
fetch_logs_from_secs_ago: 8500 # 24hs
# Anvil start with block time is 7 seconds
block_time_secs: 12

ecdsa:
    private_key_store_path: <private_key_store_path>
    private_key_store_password: <private_key_store_password>
