.PHONY: help deps dev

help:
	@echo "deps - Install the dependencies"
	@echo "dev - Start the development server"
	@echo "help - Show this help"

deps:
	@echo "Installing dependencies"
	@mix setup

dev:
	@echo "Starting development server"
	@mix phx.server
