.PHONY: help deps run

help:
	@echo "deps - Installing Elixir code dependencies"
	@echo "run - Starting the Elixir backend server"
	@echo "help - Show this help"

deps:
	@echo "Installing Elixir code dependencies"
	@mix setup

run:
	@echo "Starting the Elixir backend server"
	@mix phx.server
