[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[features]
default = []
tls = ["dep:rustls"]

[dependencies]
serde =  { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
agg_mode_sdk = { workspace = true }
prometheus = { workspace = true }
sp1-sdk = { workspace = true }
db = { workspace = true }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3.0", features = ["env-filter"] }
bincode = "1.3.3"
actix-web = { version = "4", features = ["rustls-0_23"] }
actix-multipart = "0.7.2"
actix-web-prometheus = "0.1.2"
rustls = { version = "0.23", optional = true, default-features = false, features = ["std", "aws-lc-rs"] }
alloy = { workspace = true }
tokio = { version = "1", features = ["time", "macros", "rt-multi-thread"]}
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "uuid", "bigdecimal" ] }
hex = "0.4"
