aligned_service_manager_address: "0xa82fF9aFd8f496c3d6ac40E2a0F282E47488CFc9"
proof_aggregation_service_address: "0xc351628EB244ec633d5f21fBD6621e1a683B1181"
eth_rpc_url: "http://localhost:8545"
eth_ws_url: "ws://localhost:8545"
max_proofs_in_queue: 1000
last_aggregated_block_filepath: config-files/proof-aggregator.last_aggregated_block.json

ecdsa:
    private_key_store_path: "config-files/anvil.proof-aggregator.ecdsa.key.json"
    private_key_store_password: ""
