# https://hub.docker.com/_/postgres
FROM postgres:16.3

# Environment variables
ENV POSTGRES_USER=telemetry_user
ENV POSTGRES_PASSWORD=telemetry_pass
ENV POSTGRES_DB=telemetry_db

# Expose the default PostgreSQL port
EXPOSE 5432
