[package]
name = "l2_example"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
types = { workspace = true }
lambdaworks-crypto = { workspace = true }
primitive-types = { workspace = true}
rand = "0.8"
sp1-sdk = "4.1.3"
sp1_state_transition_program = { path = "./zkvm_programs/sp1/" }
aligned-sdk = { path = "../../../../batcher/aligned-sdk" }
bincode = "1.3.3"

[build-dependencies]
sp1-build = { version = "4.1.3" } 

[profile.release]
opt-level = 3
