- name: Deploy Full Aggregation Mode Stack
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Deploy PostgreSQL Cluster
      ansible.builtin.import_playbook: postgres_cluster.yaml

    - name: Deploy Gateway and Poller on Primary
      ansible.builtin.import_playbook: gateway_stack.yaml
      vars:
        host: gateway_primary

    - name: Deploy Gateway and Poller on Secondary
      ansible.builtin.import_playbook: gateway_stack.yaml
      vars:
        host: gateway_secondary

    - name: Deploy Metrics Stack
      ansible.builtin.import_playbook: metrics_stack.yaml
      vars:
        host: metrics
