- name: Deploy Gateway and Poller Stack
  hosts: "{{ host }}"

  tasks:
    - name: Deploy Gateway
      ansible.builtin.import_playbook: gateway.yaml
      vars:
        host: "{{ host }}"

    - name: Deploy Poller
      ansible.builtin.import_playbook: poller.yaml
      vars:
        host: "{{ host }}"
