- name: Deploy Prometheus
  ansible.builtin.import_playbook: prometheus_agg_mode.yaml
  vars:
    host: "{{ host }}"
    env: "{{ env }}"

- name: Deploy Grafana
  ansible.builtin.import_playbook: grafana_agg_mode.yaml
  vars:
    host: "{{ host }}"
    env: "{{ env }}"
