volumes:
  postgres_data:

networks:
  aligned-network:
    name: aligned-network
    driver: bridge

name: aggregation-mode
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - aligned-network

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8090:8080
    networks:
      - aligned-network
