{
 "title": "Aggregation Mode",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "payments_contract",
    "query": "0xe6C9D0cf87cdaA8B2093c4b3830dde7267843F64"
   },
   {
    "name": "proof_aggregator_contract",
    "query": "0x6B34AAaE780A5EAB4c91AB8F54f2a421E9c2FB59"
   },
   {
    "name": "proof_aggregator_wallet",
    "query": "0x7EB3B63A4F3e7810Cc9bbc346749E2491Da4D7Cc"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">ETHEREUM</h1>\n</div>"
   }
  },
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "json_options": {
      "root_is_not_array": true
     },
     "method": "POST",
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"\n| project \"block_number\"=\"number\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_blockNumber\",\n  \"params\": [],\n  \"id\": 1\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Current Gas Price (GWEI)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "root_is_not_array": true
     },
     "method": "POST",
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_gasPrice\",\n  \"params\": [],\n  \"id\": 1\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">SYSTEM STATUS</h1>\n</div>"
   }
  },
  {
   "title": "Public Gateway Status (TODO)",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "targets": [
    {
     "columns": [
      { "selector": "$__response.statusCode", "text": "status", "type": "number" }
     ],
     "parser": "backend",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n  | extend status = $__response.statusCode",
     "url": "https://hoodi.gateway.alignedlayer.com",
     "url_options": { "body_content_type": "text/plain", "body_type": "raw", "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Gateway  Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"gateway\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Poller Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"poller\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Postgres Monitor",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE\n    WHEN pg_is_in_recovery() = false THEN 1\n    ELSE 0\n  END AS up;"
    }
   ]
  },
  {
   "title": "Postgres Nodes Status",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT UPPER(node.nodename), health\nFROM pgautofailover.node\nORDER BY node.nodename;"
    }
   ]
  },
  {
   "title": "Selected Primary DB",
   "type": "table",
   "gridPos": { "h": 3, "w": 7, "x": 8, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT node.nodename, node.nodehost\nFROM pgautofailover.node\nWHERE node.reportedstate = 'primary'\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "Schema Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT version, description\nFROM _sqlx_migrations\nORDER BY version DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Postgres Nodes Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT nodename, nodehost, nodeport, goalstate, reportedstate, health\nFROM pgautofailover.node;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">GATEWAY</h1>\n</div>"
   }
  },
  {
   "title": "User Errors Response Count (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "floor(\n  increase(api_response_code{job=\"gateway-http\",statuscode=~\"4..\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Errors Response Count (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "floor(\n  increase(api_response_code{job=\"gateway-http\",statuscode=~\"5..\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Responses Count (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "floor(\n  increase(api_response_code{service=\"gateway-http\",statuscode=~\"2..\",endpoint!=\"/metrics\", endpoint!=\"/\"}[$__range])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 34 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">SUBSCRIPTIONS</h1>\n</div>"
   }
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_subscriptions{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Last Processed Block",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 5, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "last_processed_block{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Payment events (placeholder)",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "dataset": "agg_mode",
     "rawSql": "SELECT \n  address as \"Address\", \n  to_char(to_timestamp(started_at), 'YYYY-MM-DD HH24:MI:SS') as \"Started At\",\n  to_char(to_timestamp(valid_until), 'YYYY-MM-DD HH24:MI:SS') as \"Valid Until\",\n  tx_hash as \"TX Hash\"\nFROM payment_events\nORDER BY \"valid_until\" DESC\n;"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 42 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">PAYMENTS CONTRACT</h1>\n</div>"
   }
  },
  {
   "title": "Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 44 },
   "options": {
    "content": "<h3 style=\"margin: 0; color: #fff; text-align: center\">${payments_contract}</h1>"
   }
  },
  {
   "title": "Subscription Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${payments_contract}\", \n      \"data\": \"0xa4ece875\" \n    }, \n    \"latest\" ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Active Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${payments_contract}\", \n      \"data\": \"0x93588bee\" \n    }, \"latest\" ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Subscription Cost (Ether)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \"jsonrpc\": \"2.0\", \"method\": \"eth_call\", \"params\": [ { \"to\": \"${payments_contract}\", \"data\": \"0x07f56ad4\" }, \"latest\" ], \"id\": 1 }",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Funds recipient",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${payments_contract}\", \n      \"data\": \"0x2c42a9dd\" \n    }, \n    \"latest\" \n    ], \n    \"id\": 1 \n  }",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Expiration time in days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${payments_contract}\", \n      \"data\": \"0x86925476\" \n    }, \n    \"latest\" \n  ],\n\"id\": 1 }",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Max Subscription Time Ahead (in days)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 15, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${payments_contract}\", \n      \"data\": \"0x051c7de3\" \n    }, \n    \"latest\" \n  ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<div style=\"background: linear-gradient(180deg, #43E188 0%, transparent 15%); padding: 8px 16px; border-radius: 4px;\">\n    <h1 style=\"margin: 0; color: #fff; text-align: center\">PROOF AGGREGATOR CONTRACT</h1>\n</div>"
   }
  },
  {
   "title": "Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 52 },
   "options": {
    "content": "<h3 style=\"margin: 0; color: #fff; text-align: center\">${proof_aggregator_contract}</h1>"
   }
  },
  {
   "title": "Owner",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${proof_aggregator_contract}\",\n      \"data\": \"0x8da5cb5b\" \n    }, \n    \"latest\" \n  ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Proof Aggregator",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${proof_aggregator_contract}\", \n      \"data\": \"0x4c46688c\" \n    }, \n  \"latest\" \n  ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "Proof Aggregator Balance in ETH",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 11, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"eth_getBalance\",\n  \"params\": [\n    \"${proof_aggregator_wallet}\",\n    \"latest\"\n  ],\n  \"id\": 1\n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "SP1 ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 58 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "columnar": false,
      "root_is_not_array": true
     },
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"${proof_aggregator_contract}\",\n        \"data\": \"0x6eecb4c9\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "SP1 Verifier Contract Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 3, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${proof_aggregator_contract}\", \n      \"data\": \"0x294e3ccb\" \n    }, \n    \"latest\" ],\n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "RISC0 ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "json_options": {
      "columnar": false,
      "root_is_not_array": true
     },
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{\n    \"jsonrpc\": \"2.0\",\n    \"method\": \"eth_call\",\n    \"params\": [\n      {\n        \"to\": \"${proof_aggregator_contract}\",\n        \"data\": \"0x972e58ba\"\n      },\n      \"latest\"\n    ],\n    \"id\": 1\n  }",
      "method": "POST"
     }
    }
   ]
  },
  {
   "title": "RISC0 Verifier Contractt Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "backend",
     "root_selector": "$.result",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"result\"",
     "url_options": {
      "body_content_type": "application/json",
      "body_type": "raw",
      "data": "{ \n  \"jsonrpc\": \"2.0\", \n  \"method\": \"eth_call\", \n  \"params\": [ \n    { \n      \"to\": \"${proof_aggregator_contract}\", \n      \"data\": \"0x616af4f7\" \n      },\n    \"latest\" \n  ], \n  \"id\": 1 \n}",
      "headers": [
       { "key": "Content-Type", "value": "application/json" }
      ],
      "method": "POST"
     }
    }
   ]
  }
 ]
}