{
 "title": "System Data",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  ETHEREUM\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  HISTORIC DATA\n</h1>"
   }
  },
  {
   "title": "Ethereum Gas Price [GWEI]",
   "type": "stat",
   "description": "Ethereum Gas Price in GWEI",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_price{job=\"aligned-tracker\"} * 10^-9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ethereum Gas Price [GWEI]",
   "type": "timeseries",
   "description": "Ethereum Gas Price evolution in GWEI",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "targets": [
    {
     "expr": "round(gas_price{job=\"aligned-tracker\"} * 10^-9 != 0, 0.00001)",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Total Proofs Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(received_proofs_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Price on Latest Batch Sent [GWEI]",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gas_price_used_on_latest_batch{job=\"aligned-batcher\"} * 10^-9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas Price on Latest Batch Sent [GWEI]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "GWEI" } },
   "targets": [
    {
     "expr": "round(gas_price_used_on_latest_batch{job=\"aligned-batcher\"} * 10^-9 != 0, 0.00001)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Tasks Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Batcher Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated cost in ETH the Batcher paid when sending Create Task or Cancel Task transactions.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(batcher_gas_cost_create_task_total{bot=\"batcher\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(batcher_gas_cost_cancel_task_total{bot=\"batcher\"}[$__range]) * 10 ^ -9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Aggregator Gas Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost in ETH the Aggregator paid when sending RespondToTask transactions.",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_total_count{bot=\"aggregator\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical - Accumulated Batcher Cost Paid [ETH]",
   "type": "stat",
   "description": "Historical accumulated cost in ETH the Batcher paid when sending Create Task or Cancel Task transactions.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(batcher_gas_cost_create_task_total{bot=\"batcher\"}[10y])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(batcher_gas_cost_cancel_task_total{bot=\"batcher\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical - Accumulated Aggregator Gas Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost in ETH the Aggregator paid when sending RespondToTask transactions.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_total_count{bot=\"aggregator\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Batcher Cancel Task Cost [ETH]",
   "type": "stat",
   "description": "Accumulated cost in ETH the Batcher paid when sending Cancel Task transactions.",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(batcher_gas_cost_cancel_task_total{bot=\"batcher\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accumulated Aggregator Extra Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit.",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_for_batcher_sum{bot=\"aggregator\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical - Accumulated Batcher Cancel Task Cost [ETH]",
   "type": "stat",
   "description": "Historical accumulated cost in ETH the Batcher paid when Canceling a Task",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(batcher_gas_cost_cancel_task_total{bot=\"batcher\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical - Accumulated Aggregator Extra Cost Paid [ETH]",
   "type": "stat",
   "description": "Accumulated gas cost the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(aligned_aggregator_gas_cost_paid_for_batcher_sum{bot=\"aggregator\"}[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Times Aggregator Paid Extra Cost",
   "type": "stat",
   "description": "Number of times the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_num_times_paid_for_batcher_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Historical - # Times Aggregator Paid Extra Cost",
   "type": "stat",
   "description": "Number of times the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_num_times_paid_for_batcher_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  SYSTEM STATUS\n</h1>"
   }
  },
  {
   "title": "Batcher Open Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "open_connections_count{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Not Verified",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "reducer": "last", "type": "math" }
   ]
  },
  {
   "title": "Total Batcher Restarts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(batcher_started_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available Data Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 17, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "available_data_services{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Batcher Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "floor(increase(batcher_started_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: black; padding: 10px; border-radius: 0px; text-align: center;\">\n  SYSTEM STATUS\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 37 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  BATCHER\n</h1>"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 37 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  AGGREGATOR\n</h1>"
   }
  },
  {
   "title": "Batches Sent",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 39 },
   "targets": [
    {
     "expr": "floor(increase(sent_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Received",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verified Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 39 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reverted Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(reverted_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Reverted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 45 },
   "targets": [
    {
     "expr": "floor(increase(reverted_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Tasks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 45 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Canceled Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(canceled_batches_count{job=\"aligned-batcher\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batches Canceled",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 51 },
   "targets": [
    {
     "expr": "floor(increase(canceled_batches_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Bumps Sending Responses to Ethereum",
   "type": "timeseries",
   "description": "Number of times gas price was bumped while sending an aggregated response.",
   "gridPos": { "h": 6, "w": 10, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "floor(increase(aligned_respond_to_task_gas_price_bumped_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_len{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 57 },
   "targets": [
    {
     "expr": "queue_len{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Times Aggregator Paid Extra Cost",
   "type": "timeseries",
   "description": "Time series showing the number of times the aggregator paid for the batcher when the tx cost was higher than the respondToTaskFeeLimit",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_num_times_paid_for_batcher_count{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "queue_size_bytes{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "queue_size_bytes{job=\"aligned-batcher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Operator Missing Tasks",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "floor(increase(missing_operator_count{job=\"aligned-tracker\"}[$__range]))",
     "legendFormat": "{{operator}}"
    }
   ]
  },
  {
   "title": "Broken websocket connections",
   "type": "timeseries",
   "description": "Measures websocket connections that were abnormally disconnected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "floor(increase(broken_ws_connections_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Operator Responses",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "floor(increase(operator_response_count{job=\"aligned-tracker\"}[$__range]))",
     "legendFormat": "{{operator}}"
    },
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks_count{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "Tasks Received"
    }
   ]
  },
  {
   "title": "# User Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "floor(increase(user_errors_count{job=\"aligned-batcher\"}[10y]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  },
  {
   "title": "Message Handler - (Batch | User) Lock Timeout",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_handler_batch_lock_timeouts_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "message_handler_user_lock_timeouts_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 92 },
   "options": {
    "content": "<h1 style=\"background-color: #00A86B; color: white; padding: 10px; border-radius: 0px; text-align: center;\">\n  Latency\n</h1>"
   }
  },
  {
   "title": "Upload Batch to S3 Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "s3_duration * 10 ^ (-3)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest respond to task latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aligned_aggregator_respond_to_task_latency{bot=\"aggregator\"}",
     "legendFormat": "Latest latency"
    }
   ]
  },
  {
   "title": "CreateNewTask Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cancel_create_new_task_duration * 10 ^ (-3)",
     "legendFormat": "cancel_new_task"
    },
    {
     "expr": "create_new_task_duration * 10 ^(-3)",
     "legendFormat": "create_new_task"
    }
   ]
  },
  {
   "title": "Latest quorum reached latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "aligned_aggregator_task_quorum_reached_latency{bot=\"aggregator\"}",
     "legendFormat": "Latest latency"
    }
   ]
  }
 ]
}