{
 "title": "Aggregator Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Batcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Aggregator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Tasks Not Verified",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "reducer": "last", "type": "math" }
   ]
  },
  {
   "title": "Verified Tasks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 2 },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Received",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregator_received_tasks{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses{bot=\"aggregator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Verified",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_aggregated_responses{bot=\"aggregator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}