{
 "title": "Operator Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total Verified Proofs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_operator_responses{bot=\"operator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Verified Proofs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(increase(aligned_operator_responses{bot=\"operator\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "floor(increase(aligned_operator_responses{bot=\"operator\"}[10y]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verification Rate per Min",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(aligned_operator_responses{bot=\"operator\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verification Rate per Sec",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aligned_operator_responses{bot=\"operator\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Verification Rate per Min",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "rate(aligned_operator_responses{bot=\"operator\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}