[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde =  { workspace = true }
tokio = { version = "1"}
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "migrate", "chrono", "uuid", "bigdecimal"] }
tracing = { version = "0.1", features = ["log"] }

[[bin]]
name = "migrate"
path = "cmd/migrate.rs"
