name: build-and-test-rust-projects

on:
  push:
    branches:
      - testnet
      - staging
  pull_request:
    branches: ["*"]
    paths:
      - "crates/**"
      - "aggregation_mode/**"
      - ".github/workflows/build-and-test-rust.yml"

jobs:
  test:
    runs-on: aligned-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.2.0


      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            crates/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-
          
      - name: Run Batcher tests
        run: |
          cd crates
          cargo test --all

      - name: Run AggregationMode tests
        run: |
          cd aggregation_mode
          cargo test --all
