name: build-and-test-rust-projects

on:
  push:
    branches:
      - testnet
      - staging
  pull_request:
    branches: ["*"]
    paths:
      - "crates/**"
      - "aggregation_mode/**"
      - ".github/workflows/build-and-test-rust.yml"

jobs:
  build-and-test:
    runs-on: aligned-runner

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.88.0
          components: rustfmt, clippy
          override: true

      - name: foundry-toolchain
        uses: foundry-rs/foundry-toolchain@v1.2.0

      # Reference: https://github.com/succinctlabs/sp1/actions/runs/8886659400/workflow#L61-L65
      - name: Install sp1 toolchain
        run: |
          curl -L https://sp1.succinct.xyz | bash
          source /home/runner/.bashrc
           ~/.sp1/bin/sp1up

      - name: Install risc0 toolchain
        run: |
          curl -L https://risczero.com/install | bash
          source ~/.bashrc
          ~/.risc0/bin/rzup install

      # Reference: https://github.com/0xPolygonHermez/zisk/blob/b3ca745b80423c8123dc24f19039865a5bc8b074/.github/workflows/test_install_bin.yml#L71-L83
      - name: Install ZisK dependencies
        shell: bash
        run: |
           sudo apt-get install -y xz-utils jq curl build-essential qemu-system libomp-dev \
                libgmp-dev nlohmann-json3-dev protobuf-compiler uuid-dev libgrpc++-dev \
                libsecp256k1-dev libsodium-dev libpqxx-dev nasm libopenmpi-dev openmpi-bin openmpi-common

      - name: Install and run ziskup
        run: |
          curl -s -o install.sh https://raw.githubusercontent.com/0xPolygonHermez/zisk/main/ziskup/install.sh
          chmod +x install.sh
          export GH_RUNNER=1
          ./install.sh

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            crates/target
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-rust-

      - name: Check formatting
        run: |
          cd crates
          cargo fmt --all -- --check

      - name: Run Clippy
        run: |
          cd crates
          # TODO: solve this issues instead of ignoring
          cargo clippy --all -- -D warnings -A clippy::uninlined_format_args

      - name: Build Batcher
        run: |
          cd crates
          cargo build --all

      - name: Check formatting of AggregationMode
        run: |
          cd aggregation_mode
          cargo fmt --all -- --check

      - name: Build AggregationMode # We build before clippy to generate the ELF
        run: |
          cd aggregation_mode
          cargo build --all

      - name: Run Clippy on AggregationMode
        run: |
          cd aggregation_mode
          # We need to skip the build as clippy does not support the riscv32im-risc0-zkvm-elf target
          RISC0_SKIP_BUILD=1 cargo clippy --all -- -D warnings

      - name: Run Batcher tests
        run: |
          cd crates
          cargo test --all

      - name: Run AggregationMode tests
        run: |
          cd aggregation_mode/proof_aggregator && SKIP_AGG_PROGRAMS_BUILD=1 cargo test
          cd ../gateway && cargo test
          cd ../payments_poller && cargo test
